### PR TITLE
Added full Esperanto translation

### PR DESCRIPTION
**Pull request by jakubfabijan**
I made full Esperanto translation of original strings.xml. I kept the specific "style" of the text 😉. ("redito" and "subredito" are common Esperanto translations for "Reddit" and "subreddit".)

---

Yes it does have support for Esperanto locale, most Esperantists are using [Locale-Changer](https://play.google.com/store/search?q=locale%20changer&c=apps&hl=en&gl=US) apps to set it on their systems. It works with every app that have `strings.xml` in `values-eo` directory.

### CODE REVIEW

**Review by Tunous — APPROVED** [review]
Thanks for the contribution. I don't know Esperanto but this looks good to me :)

**Comment by AbsurdlySuspicious** [comment]
Since this is the first translation for this project I built this branch to check nothing is broken. 

And nothing seems to be broken, which is good, but a plenty seems untranslated:
- First start gesture guide have all it's strings hardcoded so it's still in english
  - I'll open separate issue for this
- there's also some strings in `values/userpreferences.xml`
  - I guess they can be done in crowdin now (?)

Thank you for translation and being a l10n pioneer for this app :D

**Comment by Tunous** [comment]
> I guess they can be done in crowdin now

Yes, if all is configured well you can try translating it here. That's my first time setting it up so I'm not sure if anything is missing. We'll see.

**Comment by jakubfabijan** [comment]
> I don't know Esperanto

Fun fact, Esperanto is the most popular constructed language, it was made in 1887. Over 2 million people around the world speak it. Sorry if I am bothering you :stuck_out_tongue:

**Pull request merged**
