### PR TITLE
Upgrade Gradle to 6.2.1

### PR DESCRIPTION
**Pull request by msfjarvis**
Also removed the hardcoded version in build.gradle to avoid unnecessary diff churn when upgrading.

### CODE REVIEW

**Comment by msfjarvis** [comment]
I can't add the verification task through a PR, but [here's the commit](https://github.com/msfjarvis/Dawn/commit/0c0b565d36d0533bb0ea012e3782d1627a65dc42) for you to cherry-pick to master before merging this.

**Comment by msfjarvis** [comment]
Well, I was 5 seconds away from updating the branch for Gradle 6.3. I've done that anyway now, so you can probably just pick [this](https://github.com/msfjarvis/Dawn/commit/1ab0904821c1622d41f34b2b15a32cd9a46e1163) to master or I can start a new PR as per your preference.

**Comment by Tunous** [comment]
One thing I've noticed (based on https://gitlab.com/fdroid/rfp/-/issues/1320#note_331543140) is that we are missing `distributionSha256Sum` from properties. Would you be able to make a pull request which also includes required correct checksum?

**Comment by msfjarvis** [comment]
> One thing I've noticed (based on [gitlab.com/fdroid/rfp/-/issues/1320#note_331543140](https://gitlab.com/fdroid/rfp/-/issues/1320#note_331543140)) is that we are missing `distributionSha256Sum` from properties. Would you be able to make a pull request which also includes required correct checksum?

Sure, I'll check what needs to be configured to add it automatically.

**Comment by msfjarvis** [comment]
Turns out that it cannot be added automatically, because Gradle makes this manual and explicit, and F-Droid being F-Droid bumps the responsibility to downstream app developers rather than attempt to automate it on their end which would actually be rather simple. I'll add it manually for now and just take care going forward to keep doing it by hand.

**Pull request merged**
