### PR TITLE
Fix Imgur images loading

### PR DESCRIPTION
**Pull request by AbsurdlySuspicious**
Seems like Imgur changed their paid api endpoint (very clever of them) and this caused imgur albums and images to stop loading.

Imgur api docs states this:

> The Imgur API is free for non-commercial usage. Your application is probably free if you don't plan on making any money with it, or if it's open source.

So i've just changed endpoint to the free one and it works so far (albums/images). I haven't checked uploading yet but according to docs this should work too. But comment in code says:

```
  /**
   * Get images in an Imgur album. This is a paid API so we try to minimize its usage. The response
   * is wrapped in {@link Response} so that the headers can be extracted for checking Imgur rate-limits.
   */
```

\- so I don't know if I just should update this to new paid endpoint. If we decide to keep free one, then all rate-limit code probably can be removed.

### CODE REVIEW

**Comment by AbsurdlySuspicious** [comment]
I will try to find out how is rate limiting applies to free clients as of now

**Comment by AbsurdlySuspicious** [comment]
ping @saket

**Comment by saket** [comment]
Switching to free endpoints _should_ be fine. I chose to use their paid APIs because Dank wasn't open sourced back then and I had plans to introduce a paid version.

**Comment by AbsurdlySuspicious** [comment]
Upload works ok. I guess PR is ready to merge

**Comment by AbsurdlySuspicious** [comment]
@saket I think mashape token can be invalidated after merge. Old clients won't work due to endpoint change anyway

**Comment by Tunous** [comment]
Thanks, merged :)

**Pull request merged**
