### PR TITLE
Bulk dependency upgrades

### PR DESCRIPTION
**Pull request by msfjarvis**
Other updates are blocked on various incompatibilities, but these appear to be safe to upgrade. All unit tests are passing, and the app seems to work just fine but let's test drive this branch for a day or two to be sure.

### CODE REVIEW

**Comment by AbsurdlySuspicious** [comment]
I've merged this branch to my build and will report here on any problems

**Comment by AbsurdlySuspicious** [comment]
gesture-views is affected by #171. Swipe works now, but viewer still occasionally opens twice

**Comment by AbsurdlySuspicious** [comment]
Nope, swipe is still broken too

**Comment by msfjarvis** [comment]
Thanks I'm gonna take it out of this branch in a bit.

**Review by AbsurdlySuspicious — APPROVED** [review]
Other than gesture-views everything else seem to be working ok. I was worried for flexmark update, but luckily it didn't break markdownhints

**Comment by msfjarvis** [comment]
The test failure is a result of Robolectric flakiness so I'll merge this and deal with that separately.

**Comment by msfjarvis** [comment]
#374 fixes the CI flakiness, once that's merged I'll rebase this branch on master.

**Pull request merged**
