### PR TITLE
Inline text selection

### PR DESCRIPTION
**Pull request by AbsurdlySuspicious**
My attempt on making inline text selection:

dawn_sel_main
dawn_sel_md

- Collapse, swipe actions, link longpress works
- Collapsed comments can't be selected
- Touch ripple works
- Most of markdown blocks selects properly

Bugs:
- Monospace markdown blocks have invisible selection (copy works, though)

### CODE REVIEW

**Comment by AbsurdlySuspicious** [comment]
Solves (replaces?) #89

**Comment by Tunous** [comment]
Wow, great work! That is definitely better than my poor workaround with selection dialog :D
I’ll test whether this works on my phone too.

> Submission title selection
> Submission text selection

I would suggest creating a separate pull request for these two since they are dealing with different interface elements.

**Comment by saket** [comment]
nice!

**Comment by AbsurdlySuspicious** [comment]
> I would suggest creating a separate pull request for these two since they are dealing with different interface elements.
fixed task list

**Comment by AbsurdlySuspicious** [comment]
Bug with monospace blocks also appears with selftext selection too and probably needs to be solved separately as well, so I will undraft this

**Comment by AbsurdlySuspicious** [comment]
Done

**Pull request merged**
