### PR TITLE
Large image previews

### PR DESCRIPTION
**Pull request by Tunous**
| Settings | Preview |
| --- | --- |
|  |  |

Related to #25

### CODE REVIEW

**Comment by msfjarvis** [comment]
Been using it for a few days, works perfectly on my Pixel 2 and Samsung M30s :+1:

**Comment by Esselans** [comment]
Maybe you could add a bit of padding or margin between submissions? For me at least in some subreddit it's a bit confusing which title is for image since they're all together. Other than that it works fine.

**Comment by Tunous** [comment]
> Maybe you could add a bit of padding or margin between submissions?

Done. I've added additional margin above each image:

**Comment by Esselans** [comment]
Nicely done!

**Comment by saket** [comment]
Nice! The gray line separators look redundant in my opinion.

**Comment by Tunous** [comment]
I've moved the separators so they don't look so out of place when there is a big image below them.

**Pull request merged**
