### PR TITLE
Fix Gfycat integration

### PR DESCRIPTION
**Pull request by msfjarvis**
Gfycat changed the API response yet again :shrug:

The new JSON key is taken from the example in their [wiki](https://github.com/Redgifs/api/wiki/Get-gif-info).

### CODE REVIEW

**Review by Tunous — APPROVED** [review]

**Comment by hydrargyrum** [comment]
@Tunous maybe that would be worth making a new release so this fix reaches f-droid?

**Comment by Tunous** [comment]
Sure, I'll prepare play store and f-droid releases this weekend.

**Comment by hydrargyrum** [comment]
@Tunous actually, redgifs integration is still broken :(

**Comment by msfjarvis** [comment]
> @Tunous actually, redgifs integration is still broken :( 

It's a bit iffy, the services (gfycat and redgifs) like to both diverge and redirect to each other which makes this fairly hard to do. I had a WIP refactor of all of this code somewhere which fixes some of these problems, I'll try to find and clean it up sometime next week.

**Pull request merged**
