### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by Tunous**

### CODE REVIEW

**Comment by msfjarvis** [comment]
We need to pare down the frequency of these...

**Comment by Tunous** [comment]
Right now it will update every hour only the files that are translated 100% in given language.

**Comment by Tunous** [comment]
Changed it to once a day, that's the longest duration I see.

**Comment by msfjarvis** [comment]
CI won't run until a human event triggers it :shrug:

**Comment by Tunous** [comment]
That's on purpose so it won't unnecessarily use servers. We can just run it once before merge.

**Pull request merged**
